GET http://localhost:3000/users


###


GET http://localhost:3000/users/62f2b9c9e1eae07f3ecffd55


###


POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Todd",
    "createdDate": "8/9/2022",
    "email": "todd@email.com"
}


###


DELETE http://localhost:3000/users/62f2be30ea1c1684835cda98